package com.smartagenda.api;
import jakarta.servlet.http.HttpSession;
import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/disponibilidad") public class DisponibilidadController {
 private final JdbcTemplate jdbc; public DisponibilidadController(JdbcTemplate j){jdbc=j;}
 @GetMapping public List<Map<String,Object>> list(@RequestParam int idProfesional){return jdbc.queryForList("SELECT * FROM disponibilidad WHERE idProfesional=? ORDER BY FIELD(diaSemana,'Lunes','Martes','Miercoles','Jueves','Viernes','Sabado','Domingo')",idProfesional);}
 @PostMapping public Map<String,Object> create(@RequestBody Map<String,Object>b,HttpSession s){Map<String,Object>u=SessionSupport.role(s,"Profesional","Administrador");String dia=AuthController.text(b,"diaSemana"),inicio=AuthController.text(b,"horaInicio"),fin=AuthController.text(b,"horaFin");int intervalo=AuthController.number(b,"intervaloMin",30),p=AuthController.number(b,"idProfesional",u.get("idProfesional")==null?0:((Number)u.get("idProfesional")).intValue());if(dia.isBlank()||inicio.isBlank()||fin.isBlank()||p<=0)throw new ApiException(HttpStatus.BAD_REQUEST,"Datos incompletos");if(fin.compareTo(inicio)<=0)throw new ApiException(HttpStatus.BAD_REQUEST,"La hora de fin debe ser posterior a la de inicio");if(jdbc.queryForObject("SELECT COUNT(*) FROM disponibilidad WHERE idProfesional=? AND diaSemana=?",Integer.class,p,dia)>0)throw new ApiException(HttpStatus.CONFLICT,"Ya existe configuración para ese día. Use PUT para actualizar.");jdbc.update("INSERT INTO disponibilidad(diaSemana,horaInicio,horaFin,intervaloMin,idProfesional) VALUES(?,?,?,?,?)",dia,inicio,fin,intervalo,p);return Map.of("message","Disponibilidad configurada","id",jdbc.queryForObject("SELECT LAST_INSERT_ID()",Integer.class));}
 @PutMapping public Map<String,String> update(@RequestBody Map<String,Object>b,HttpSession s){SessionSupport.role(s,"Profesional","Administrador");int id=AuthController.number(b,"idDisponibilidad",0);if(id<=0)throw new ApiException(HttpStatus.BAD_REQUEST,"ID requerido");List<String>f=new ArrayList<>();List<Object>p=new ArrayList<>();for(String k:List.of("horaInicio","horaFin","intervaloMin"))ProfesionalController.add(b,k,f,p);if(f.isEmpty())throw new ApiException(HttpStatus.BAD_REQUEST,"No hay datos para actualizar");p.add(id);jdbc.update("UPDATE disponibilidad SET "+String.join(",",f)+" WHERE idDisponibilidad=?",p.toArray());return Map.of("message","Disponibilidad actualizada");}
 @DeleteMapping public Map<String,String> delete(@RequestParam int id,HttpSession s){SessionSupport.role(s,"Profesional","Administrador");jdbc.update("DELETE FROM disponibilidad WHERE idDisponibilidad=?",id);return Map.of("message","Disponibilidad eliminada");}
}
