package com.smartagenda.api;
import java.time.*;
import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/recomendaciones") public class RecomendacionController {
 private final JdbcTemplate jdbc; public RecomendacionController(JdbcTemplate jdbc){this.jdbc=jdbc;}
 @GetMapping public Map<String,Object> get(@RequestParam int idProfesional,@RequestParam int idServicio,@RequestParam String fecha){Integer duration;try{duration=jdbc.queryForObject("SELECT duracionMin FROM servicio WHERE idServicio=? AND idProfesional=?",Integer.class,idServicio,idProfesional);}catch(org.springframework.dao.EmptyResultDataAccessException e){throw new ApiException(HttpStatus.NOT_FOUND,"Servicio no encontrado");}String day=switch(LocalDate.parse(fecha).getDayOfWeek()){case MONDAY->"Lunes";case TUESDAY->"Martes";case WEDNESDAY->"Miercoles";case THURSDAY->"Jueves";case FRIDAY->"Viernes";case SATURDAY->"Sabado";case SUNDAY->"Domingo";};List<Map<String,Object>> availability=jdbc.queryForList("SELECT * FROM disponibilidad WHERE idProfesional=? AND diaSemana=?",idProfesional,day);if(availability.isEmpty())return Map.of("error","El profesional no atiende ese día","slots",List.of());Map<String,Object> row=availability.getFirst();List<Map<String,Object>> appointments=jdbc.queryForList("SELECT horaInicio,horaFin FROM turno WHERE idProfesional=? AND fecha=? AND estado IN ('pendiente','confirmado')",idProfesional,fecha);LocalTime start=time(row.get("horaInicio")),end=time(row.get("horaFin"));int interval=((Number)row.get("intervaloMin")).intValue();List<Map<String,Object>> slots=new ArrayList<>();for(LocalTime current=start;!current.plusMinutes(duration).isAfter(end);current=current.plusMinutes(interval)){final LocalTime slotStart=current;final LocalTime finish=slotStart.plusMinutes(duration);boolean free=appointments.stream().noneMatch(a->slotStart.isBefore(time(a.get("horaFin")))&&finish.isAfter(time(a.get("horaInicio"))));if(free){int score=(slotStart.getHour()>=8&&slotStart.getHour()<=11)?60:50;Map<String,Object> slot=new LinkedHashMap<>();slot.put("horaInicio",slotStart.toString());slot.put("horaFin",finish.toString());slot.put("duracionMin",duration);slot.put("puntaje",score);slot.put("recomendado",false);slots.add(slot);}}slots.stream().sorted((a,b)->Integer.compare((int)b.get("puntaje"),(int)a.get("puntaje"))).limit(3).forEach(s->s.put("recomendado",true));return Map.of("fecha",fecha,"diaSemana",day,"profesional",idProfesional,"servicio",idServicio,"duracionServicio",duration,"totalSlots",slots.size(),"slots",slots);}
 private LocalTime time(Object value){return value instanceof java.sql.Time t?t.toLocalTime():LocalTime.parse(String.valueOf(value));}
}
