package com.smartagenda.api;
import jakarta.servlet.http.HttpSession;
import java.time.LocalDate;
import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/reportes") public class ReporteController {
 private final JdbcTemplate jdbc; public ReporteController(JdbcTemplate jdbc){this.jdbc=jdbc;}
 @GetMapping public Object get(@RequestParam(defaultValue="general")String tipo,@RequestParam(required=false)String fechaDesde,@RequestParam(required=false)String fechaHasta,@RequestParam(required=false)Integer idProfesional,HttpSession s){Map<String,Object>user=SessionSupport.user(s);if("rubros".equals(tipo))return jdbc.queryForList("SELECT * FROM rubro ORDER BY nombre");if(!"general".equals(tipo))throw new ApiException(HttpStatus.BAD_REQUEST,"Tipo de reporte no válido");String role=String.valueOf(user.get("rol"));if("Cliente".equals(role))throw new ApiException(HttpStatus.FORBIDDEN,"No tiene permisos para ver reportes");if("Profesional".equals(role))idProfesional=SessionSupport.intValue(user,"idProfesional");String from=fechaDesde==null?LocalDate.now().withDayOfMonth(1).toString():fechaDesde,to=fechaHasta==null?LocalDate.now().withDayOfMonth(LocalDate.now().lengthOfMonth()).toString():fechaHasta;String filter="t.fecha BETWEEN ? AND ?"+(idProfesional==null?"":" AND t.idProfesional=?");List<Object>p=idProfesional==null?List.of(from,to):List.of(from,to,idProfesional);Map<String,Object>r=new LinkedHashMap<>();r.put("turnosPorEstado",jdbc.queryForList("SELECT estado,COUNT(*) total FROM turno t WHERE "+filter+" GROUP BY estado",p.toArray()));r.put("turnosPorDia",jdbc.queryForList("SELECT fecha,COUNT(*) total FROM turno t WHERE "+filter+" GROUP BY fecha ORDER BY fecha",p.toArray()));r.put("serviciosTop",jdbc.queryForList("SELECT s.nombre,COUNT(*) total FROM turno t JOIN servicio s ON t.idServicio=s.idServicio WHERE "+filter+" GROUP BY s.idServicio,s.nombre ORDER BY total DESC LIMIT 5",p.toArray()));int total=jdbc.queryForObject("SELECT COUNT(*) FROM turno t WHERE "+filter,Integer.class,p.toArray()),confirmed=jdbc.queryForObject("SELECT COUNT(*) FROM turno t WHERE "+filter+" AND estado IN ('confirmado','finalizado')",Integer.class,p.toArray()),cancelled=jdbc.queryForObject("SELECT COUNT(*) FROM turno t WHERE "+filter+" AND estado='cancelado'",Integer.class,p.toArray());Double money=jdbc.queryForObject("SELECT COALESCE(SUM(s.precio),0) FROM turno t JOIN servicio s ON t.idServicio=s.idServicio WHERE "+filter+" AND t.estado IN ('confirmado','finalizado')",Double.class,p.toArray());r.put("tasaOcupacion",total==0?0:Math.round((confirmed*1000.0/total))/10.0);r.put("totalCancelaciones",cancelled);r.put("totalTurnos",total);r.put("ingresos",money);return r;}
}
