package com.smartagenda.api;
import jakarta.servlet.http.HttpSession;
import java.math.BigDecimal;
import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/servicios") public class ServicioController {
 private final JdbcTemplate jdbc; public ServicioController(JdbcTemplate j){jdbc=j;}
 @GetMapping public Object list(@RequestParam(required=false)Integer id,@RequestParam(required=false)Integer idProfesional){String base="SELECT s.*,p.nombreNegocio FROM servicio s JOIN profesional p ON s.idProfesional=p.idProfesional ";if(id!=null){try{return jdbc.queryForMap(base+"WHERE s.idServicio=?",id);}catch(org.springframework.dao.EmptyResultDataAccessException e){throw new ApiException(HttpStatus.NOT_FOUND,"Servicio no encontrado");}}return idProfesional==null?jdbc.queryForList(base+"WHERE s.estado='activo' ORDER BY p.nombreNegocio,s.nombre"):jdbc.queryForList(base+"WHERE s.idProfesional=? AND s.estado='activo' ORDER BY s.nombre",idProfesional);}
 @PostMapping public Map<String,Object> create(@RequestBody Map<String,Object>b,HttpSession s){Map<String,Object>u=SessionSupport.role(s,"Profesional","Administrador");String n=AuthController.text(b,"nombre");int d=AuthController.number(b,"duracionMin",0),pId=AuthController.number(b,"idProfesional",u.get("idProfesional")==null?0:((Number)u.get("idProfesional")).intValue());BigDecimal precio=new BigDecimal(AuthController.text(b,"precio"));if(n.isBlank()||d<=0||pId<=0||precio.signum()<=0)throw new ApiException(HttpStatus.BAD_REQUEST,"Datos incompletos o inválidos");if(jdbc.queryForObject("SELECT COUNT(*) FROM servicio WHERE nombre=? AND idProfesional=? AND estado='activo'",Integer.class,n,pId)>0)throw new ApiException(HttpStatus.CONFLICT,"Ya existe un servicio con ese nombre");jdbc.update("INSERT INTO servicio(nombre,descripcion,duracionMin,precio,idProfesional) VALUES(?,?,?,?,?)",n,AuthController.text(b,"descripcion"),d,precio,pId);return Map.of("message","Servicio creado exitosamente","id",jdbc.queryForObject("SELECT LAST_INSERT_ID()",Integer.class));}
 @PutMapping public Map<String,String> update(@RequestBody Map<String,Object>b,HttpSession s){SessionSupport.role(s,"Profesional","Administrador");int id=AuthController.number(b,"idServicio",0);if(id<=0)throw new ApiException(HttpStatus.BAD_REQUEST,"ID de servicio requerido");List<String>f=new ArrayList<>();List<Object>p=new ArrayList<>();for(String k:List.of("nombre","descripcion","duracionMin","precio","estado"))ProfesionalController.add(b,k,f,p);if(f.isEmpty())throw new ApiException(HttpStatus.BAD_REQUEST,"No hay datos para actualizar");p.add(id);jdbc.update("UPDATE servicio SET "+String.join(",",f)+" WHERE idServicio=?",p.toArray());return Map.of("message","Servicio actualizado correctamente");}
 @DeleteMapping public Map<String,String> delete(@RequestParam int id,HttpSession s){SessionSupport.role(s,"Profesional","Administrador");if(jdbc.queryForObject("SELECT COUNT(*) FROM turno WHERE idServicio=? AND estado IN ('pendiente','confirmado')",Integer.class,id)>0)throw new ApiException(HttpStatus.CONFLICT,"No se puede eliminar: hay turnos pendientes asociados");jdbc.update("UPDATE servicio SET estado='inactivo' WHERE idServicio=?",id);return Map.of("message","Servicio eliminado correctamente");}
}
